# configs/base.yaml
defaults:
  - _self_

# データセット
data_root : '/home/dcuser/data/ActiveSeisField/'
train_field_list: train_field_list_wotstkres.txt
valid_field_list: train_field_list_tstkres.txt
file_size: null

# パス関連
suffix: 'edgenext_small.usi_in1k_finetune_augspace01_mask_replace03'

# モデル関連（共通部分）
backbone: edgenext_small.usi_in1k  # caformer_b36.sail_in22k_ft_in1k |edgenext_small.usi_in1k convnextv2_base.fcmae_ft_in22k_in1k_384
drop_path_rate: 0

# 一般設定
num_workers: 16
k: 1.0

use_ema: True
use_amp: True
ema_decay: 0.99

device: 'cuda:1'

# Training task
task: fb_seg  # recon | fb_seg

# 学習設定
batch_size: 16
steps_per_epoch: 2000
lr: 1e-5
lr_milestones: []
momentum: 0.9
weight_decay: 0.0001
lr_gamma: 0.2
lr_warmup_epochs: 10
val_steps: 50
epoch_block: 20
num_block: 10
print_freq: 100
resume:   /workspace/proc/result/recon/train_field_list_edgenext_small/checkpoint.pth
start_epoch: 0

# Freeze schedule
freeze_epochs: 2
unfreeze_steps: 2
resume_exclude_head: true  # skip loading head weights when resuming
resume_exclude_prefixes:
  - seg_head

# 損失係数
lambda_g1v: 1.0
lambda_g2v: 1.0

# 分散学習
distributed: False
local_rank: 0
sync_bn: True
world_size: 2
dist_url: env://

# ログ
tensorboard: true

snr:
  pre_len: 100
  post_len: 100
  guard: 12
  seed: 12345
  passes_batch: 4
  mask_ratio_for_eval: ${dataset.mask_ratio}
  mask_noise_mode: ${dataset.mask_mode}
  noise_std: ${dataset.mask_noise_std}

dataset:
  mask_ratio: 0.3
  mask_mode: replace         # replace | add
  mask_noise_std: 1
  target_mode: ${task}
  label_sigma: 5.0
  flip: True
  augment:
    time:
      prob: 0
      range: [0.9, 1.1]
    space:
        prob: 0.3
        range: [0.9, 1.1]
    freq:
      prob: 0
      kinds: [bandpass, lowpass, highpass]
      band:  [0.05, 0.45]
      width: [0.12, 0.35]
      roll:  0.02
      restandardize: true



# Loss configuration
loss:
  shift_robust: true    # set true for replace-mode training
  max_shift: 5
  fb_seg:
    type: kl   # "kl" or "mse"
    tau: 1.0   # softmax 温度
    eps: 0.02  # ラベルスムージング(0..0.05 程度)
    smooth_lambda: 0      # 0 => disabled (backward compatible)
    smooth_weight: inv      # inv | exp
    smooth_scale: 1.0       # inv: denominator epsilon; exp: inverse temperature
